import { credentialStorage } from '../auth/credentialStorage';
import { createSessionStore } from '../auth/sessionStore';
export type { Session } from '../auth/sessionStore';
const store = createSessionStore(credentialStorage);
export const getSession = store.getSession;
export const getAuthState = store.getState;
export const subscribeSession = store.subscribe;
export const restoreSession = store.restore;
export const saveSession = store.save;
export const invalidateSession = store.invalidate;
export const clearSession = store.clear;
