import { Pressable, StyleSheet, Text, View } from 'react-native';
import type { ExtraEventType } from '../types/api';
import { colors, hardShadow } from '../theme/theme';
type Props = { busy?: boolean; savingRuns: number | null; savingWicket: boolean; savingExtra: boolean; onRuns: (runs: number) => void; onWicket: () => void; onExtra: (eventType: ExtraEventType) => void; };
export default function InningsScoringControls({ busy = false, savingRuns, savingWicket, savingExtra, onRuns, onWicket, onExtra }: Props) {
  const disabled = busy || savingRuns !== null || savingWicket || savingExtra;
  return <View>
    <View style={styles.heading}><Text style={styles.title}>Score this ball</Text><Text style={styles.hint}>TAP TO RECORD</Text></View>
    <View style={styles.grid}>{[0, 1, 2, 3, 4, 6].map(runs => <Pressable key={runs} accessibilityRole="button" accessibilityLabel={runs === 0 ? 'Dot ball, no runs' : `${runs} runs`} accessibilityState={{ disabled, busy: savingRuns === runs }} disabled={disabled} onPress={() => onRuns(runs)} style={({ pressed }) => [styles.run, runs >= 4 && { backgroundColor: colors.lime }, pressed && styles.pressed, disabled && styles.disabled]}><Text style={styles.number}>{savingRuns === runs ? '…' : runs}</Text><Text style={styles.caption}>{runs === 0 ? 'DOT' : runs === 4 ? 'FOUR' : runs === 6 ? 'SIX' : runs === 1 ? 'RUN' : 'RUNS'}</Text></Pressable>)}</View>
    <View style={styles.extras}>{(['WIDE', 'NO_BALL'] as const).map(eventType => <Pressable key={eventType} accessibilityRole="button" accessibilityState={{ disabled }} disabled={disabled} onPress={() => onExtra(eventType)} style={({ pressed }) => [styles.extra, pressed && styles.pressed, disabled && styles.disabled]}><Text style={styles.extraText}>{eventType === 'WIDE' ? 'Wide' : 'No ball'} <Text style={styles.plus}>+1</Text></Text></Pressable>)}<Pressable accessibilityRole="button" accessibilityState={{ disabled, busy: savingWicket }} disabled={disabled} onPress={onWicket} style={({ pressed }) => [styles.extra, { backgroundColor: colors.coral }, pressed && styles.pressed, disabled && styles.disabled]}><Text style={styles.extraText}>{savingWicket ? 'Saving…' : 'Wicket'}</Text></Pressable></View>
  </View>;
}
const styles = StyleSheet.create({ heading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 6, marginBottom: 12 }, title: { color: colors.ink, fontSize: 18, fontWeight: '800', letterSpacing: -0.3 }, hint: { color: colors.muted, fontSize: 9, letterSpacing: 1 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 14 }, run: { ...hardShadow, flexBasis: '30%', flexGrow: 1, minHeight: 76, backgroundColor: colors.white, borderWidth: 1.5, borderColor: colors.ink, borderRadius: 5, alignItems: 'center', justifyContent: 'center', padding: 8 }, number: { color: colors.ink, fontSize: 30, fontWeight: '900', fontVariant: ['tabular-nums'] }, caption: { color: colors.ink, fontSize: 9, fontWeight: '700', letterSpacing: 1, marginTop: 2 }, extras: { flexDirection: 'row', gap: 8 }, extra: { flex: 1, minHeight: 50, paddingHorizontal: 6, paddingVertical: 10, borderWidth: 1.5, borderColor: colors.ink, borderRadius: 4, backgroundColor: colors.lavender, alignItems: 'center', justifyContent: 'center' }, extraText: { color: colors.ink, fontSize: 13, fontWeight: '800', textAlign: 'center' }, plus: { fontWeight: '400' }, pressed: { transform: [{ translateY: 2 }, { translateX: 2 }], boxShadow: '0px 0px 0px transparent' }, disabled: { opacity: 0.5 } });
