import { ScrollView, StyleSheet, Text, View } from 'react-native';
import type { Scorecard } from '../types/api';
import { colors } from '../theme/theme';
const value = (number: number | null) => number === null ? '—' : number.toFixed(1);
export default function ScorecardDetails({ card }: { card: Scorecard }) {
  return <View>
    <Text style={styles.heading}>Batting</Text>
    <ScrollView horizontal showsHorizontalScrollIndicator contentContainerStyle={{ flexGrow: 1 }}><View style={{ minWidth: 340, flex: 1 }}>
      <View style={styles.tableHeader}><Text style={[styles.columnHeading, styles.playerColumn]}>BATTER</Text>{['R', 'B', '4s', '6s', 'SR'].map(label => <Text key={label} style={[styles.columnHeading, styles.cell]}>{label}</Text>)}</View>
      {card.batting.map(player => <View key={player.id} style={styles.tableRow}><View style={styles.playerColumn}><Text style={styles.name}>{player.name}</Text><Text style={styles.status}>{player.isOut ? 'out' : 'not out'}</Text></View>{[player.runs, player.balls, player.fours, player.sixes, value(player.strikeRate)].map((stat, index) => <Text key={index} style={[styles.cell, index === 0 && styles.bold]}>{stat}</Text>)}</View>)}
    </View></ScrollView>
    <Text style={styles.heading}>Bowling</Text>
    <ScrollView horizontal showsHorizontalScrollIndicator contentContainerStyle={{ flexGrow: 1 }}><View style={{ minWidth: 340, flex: 1 }}>
      <View style={styles.tableHeader}><Text style={[styles.columnHeading, styles.playerColumn]}>BOWLER</Text>{['O', 'R', 'W', 'ECON'].map(label => <Text key={label} style={[styles.columnHeading, styles.bowlingCell]}>{label}</Text>)}</View>
      {card.bowling.map(player => <View key={player.id} style={styles.tableRow}><Text style={[styles.name, styles.playerColumn]}>{player.name}</Text>{[player.overs, player.runs, player.wickets, value(player.economy)].map((stat, index) => <Text key={index} style={[styles.bowlingCell, index === 2 && styles.bold]}>{stat}</Text>)}</View>)}
    </View></ScrollView>
    <View style={styles.extras}><View style={{ flex: 1 }}><Text style={styles.name}>{card.extras.total} extras</Text><Text style={styles.stat}>{card.extras.wides} wides · {card.extras.noBalls} no-balls</Text></View><View><Text style={styles.name}>{value(card.runRate)}</Text><Text style={styles.status}>RUN RATE</Text></View></View>
    <Text style={styles.heading}>Fall of wickets</Text>
    {card.fallOfWickets.length ? card.fallOfWickets.map(fall => <View key={fall.wicket} style={styles.detailRow}><Text style={styles.score}>{fall.runs}/{fall.wicket}</Text><Text style={[styles.stat, { flex: 1 }]}>{fall.playerName}</Text><Text style={styles.stat}>{fall.overs} ov</Text></View>) : <Text style={styles.stat}>No wickets down.</Text>}
    <Text style={styles.heading}>Partnerships</Text>
    {card.partnerships.map(partnership => <View key={partnership.wicket} style={styles.partnership}><Text style={styles.name}>{partnership.players.join(' & ')}{partnership.players.length < 2 ? ' & partner unrecorded' : ''}</Text><Text style={styles.stat}><Text style={styles.bold}>{partnership.runs} runs</Text> · {partnership.balls} balls · {partnership.ended ? 'ended' : 'unbroken'}</Text><View style={styles.track}><View style={[styles.bar, { width: `${Math.min(100, partnership.runs / Math.max(1, ...card.partnerships.map(item => item.runs)) * 100)}%` }]} /></View></View>)}
    {!card.partnerships.length ? <Text style={styles.stat}>The story starts with the first ball.</Text> : null}
    <Text style={styles.heading}>Over by over</Text>
    {card.overs.map(over => <View key={over.over} style={styles.detailRow}><Text style={styles.over}> {over.over} </Text><View style={{ flex: 1 }}><Text style={styles.name}>{over.runs} runs · {over.wickets} wickets</Text><Text style={styles.status}>{over.legalBalls} legal balls · {over.extras} extras</Text></View><Text style={styles.score}>{over.totalRuns}/{over.totalWickets}</Text></View>)}
    {!card.overs.length ? <Text style={styles.stat}>No overs recorded yet.</Text> : null}
  </View>;
}
const styles = StyleSheet.create({ heading: { color: colors.ink, fontSize: 19, fontWeight: '800', letterSpacing: -0.4, marginTop: 22, marginBottom: 12 }, tableHeader: { flexDirection: 'row', backgroundColor: colors.subtle, paddingVertical: 10, alignItems: 'center' }, tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderColor: colors.line, paddingVertical: 12, alignItems: 'center' }, columnHeading: { color: colors.muted, fontWeight: '700', fontSize: 10 }, playerColumn: { flex: 1, paddingRight: 8, paddingLeft: 6, minWidth: 120 }, cell: { width: 42, textAlign: 'right', paddingRight: 4, fontSize: 12, color: colors.ink, fontVariant: ['tabular-nums'] }, bowlingCell: { width: 48, textAlign: 'right', paddingRight: 4, fontSize: 12, color: colors.ink, fontVariant: ['tabular-nums'] }, name: { color: colors.ink, fontWeight: '700', fontSize: 14 }, status: { color: colors.muted, fontSize: 10, marginTop: 4 }, bold: { color: colors.ink, fontWeight: '800' }, stat: { color: colors.muted, fontSize: 12, lineHeight: 21 }, extras: { backgroundColor: colors.lavender, padding: 14, marginTop: 18, borderRadius: 4, flexDirection: 'row', gap: 10 }, detailRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 12, borderBottomWidth: 1, borderColor: colors.line }, score: { color: colors.ink, fontSize: 15, fontWeight: '800', fontVariant: ['tabular-nums'] }, partnership: { paddingVertical: 10 }, track: { height: 6, backgroundColor: colors.subtle, marginTop: 8, borderRadius: 2, overflow: 'hidden' }, bar: { height: 6, backgroundColor: colors.ink }, over: { backgroundColor: colors.lime, borderWidth: 1, borderColor: colors.ink, padding: 5, color: colors.ink, fontSize: 12, fontWeight: '800' } });
