import './setupIntegration.js';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';
import { prisma } from '../src/services/database.js';
import { createTeam, addPlayer, listTeams, RosterError } from '../src/services/rosterService.js';
import { createMatch, startMatch, getMatch } from '../src/services/matchService.js';
import { recordScore, recordWicket, recordExtra, addNewBatsman, changeBowler, endInnings, startSecondInnings, getInnings } from '../src/services/scoringService.js';
import { ActionConflict, undoAction } from '../src/services/actions.js';

const key = () => randomUUID();
test('undo, idempotency, saved player identities, statistics and innings boundaries work together', async () => {
  const user = await prisma.user.create({ data: { email: `${key()}@example.test`, passwordHash: 'test-only' } });
  const other = await prisma.user.create({ data: { email: `${key()}@example.test`, passwordHash: 'test-only' } });
  try {
    const team1 = await createTeam(user.id, 'Tigers');
    const team2 = await createTeam(user.id, 'Rangers');
    for (const name of ['A', 'B', 'E']) await addPlayer(user.id, team1.id, name);
    for (const name of ['C', 'D']) await addPlayer(user.id, team2.id, name);
    assert.deepEqual(await listTeams(other.id), []);
    await assert.rejects(addPlayer(other.id, team1.id, 'Intruder'), RosterError);
    await assert.rejects(createTeam(user.id, ' tigers '));
    await assert.rejects(addPlayer(user.id, team1.id, ' a '));
    await assert.rejects(createMatch({ team1Name: team1.name, team2Name: team2.name, team1Id: team1.id, team2Id: team2.id, oversLimit: 2 }, other.id), RosterError);
    const match = await createMatch({ team1Name: team1.name, team2Name: team2.name, team1Id: team1.id, team2Id: team2.id, oversLimit: 2 }, user.id);
    const started = await startMatch(match.id, { battingFirstTeam: team1.name, strikerName: 'A', nonStrikerName: 'B', bowlerName: 'C' });
    const id = started.innings[0].id;
    const initial = (await getInnings(id))!;
    assert.equal(initial.canUndo, false);
    assert.ok(initial.players.every(player => player.playerId));
    const requestId = key();
    const command = { requestId, revision: initial.match.revision };
    const scored = await recordScore(id, 4, command);
    assert.equal(scored.runs, 4);
    assert.equal((await recordScore(id, 4, command)).runs, 4);
    assert.equal(await prisma.ballEvent.count({ where: { inningsId: id } }), 1);
    await assert.rejects(recordScore(id, 6, command), ActionConflict);
    await assert.rejects(recordScore(id, 1, { requestId: key(), revision: initial.match.revision }), ActionConflict);
    const undoId = key();
    const undone = await undoAction(id, { requestId: undoId, revision: scored.match.revision });
    assert.equal(undone.runs, 0);
    assert.equal(undone.canUndo, false);
    assert.equal((await undoAction(id, { requestId: undoId })).runs, 0);
    assert.equal((await recordScore(id, 4, command)).runs, 0, 'retrying an undone action never replays it');
    await assert.rejects(undoAction(id), ActionConflict);
    for (let i = 0; i < 5; i++) await recordScore(id, 0);
    const beforeBoundary = (await getInnings(id))!;
    await recordScore(id, 1);
    const afterBoundaryUndo = await undoAction(id);
    assert.equal(afterBoundaryUndo.completedOvers, 0);
    assert.equal(afterBoundaryUndo.ballsInCurrentOver, 5);
    assert.deepEqual(afterBoundaryUndo.players, beforeBoundary.players);
    await recordWicket(id);
    await addNewBatsman(id, 'E');
    await changeBowler(id, 'D');
    assert.equal((await undoAction(id)).players.some(player => player.activeRole === 'BOWLER'), false);
    assert.equal((await undoAction(id)).players.some(player => player.playerName === 'E'), false);
    const restored = await undoAction(id);
    assert.deepEqual(restored.players, beforeBoundary.players);
    assert.equal(restored.wickets, 0);
    await recordExtra(id, 'WIDE');
    await recordExtra(id, 'NO_BALL');
    await undoAction(id);
    const details = (await getMatch(match.id))!;
    assert.deepEqual(details.innings[0].scorecard.extras, { wides: 1, noBalls: 0, total: 1 });
    assert.equal(details.innings[0].scorecard.partnerships[0].runs, 1);
    assert.deepEqual(details.innings[0].scorecard.partnerships[0].players, ['A', 'B']);
    await endInnings(id);
    const reopened = await undoAction(id);
    assert.equal(reopened.status, 'IN_PROGRESS');
    assert.equal(reopened.match.target, null);
    await endInnings(id);
    const second = await startSecondInnings(match.id, { strikerName: 'C', nonStrikerName: 'D', bowlerName: 'A' });
    assert.equal(second.match.target, 2);
    await assert.rejects(undoAction(id), ActionConflict);
    const win = await recordScore(second.id, 6);
    assert.equal(win.match.status, 'COMPLETED');
    assert.ok(win.match.result);
    const correction = await undoAction(second.id);
    assert.equal(correction.match.status, 'IN_PROGRESS');
    assert.equal(correction.match.result, null);
    assert.equal(correction.match.winner, null);
    assert.equal(correction.match.target, 2);
    assert.equal(correction.status, 'IN_PROGRESS');
    assert.equal(correction.runs, 0);
    const roster = await listTeams(user.id);
    const c = roster.find(team => team.id === team2.id)!.players.find(player => player.name === 'C')!;
    assert.equal(c.stats.runs, 0, 'career batting totals follow undo');
    assert.equal(c.stats.matches, 1, 'batting and bowling in one match count once');
    assert.equal(c.stats.runsConceded, 1);
    const boundaryMatch = await createMatch({ team1Name: 'Boundary A', team2Name: 'Boundary B', oversLimit: 1 }, user.id);
    const boundaryStart = await startMatch(boundaryMatch.id, { battingFirstTeam: 'Boundary A', strikerName: 'P', nonStrikerName: 'Q', bowlerName: 'R' });
    const boundaryId = boundaryStart.innings[0].id;
    for (let i = 0; i < 5; i++) await recordScore(boundaryId, 0);
    const endedByWicket = await recordWicket(boundaryId);
    assert.equal(endedByWicket.status, 'COMPLETED');
    assert.equal(endedByWicket.match.target, 1);
    const wicketUndone = await undoAction(boundaryId);
    assert.equal(wicketUndone.status, 'IN_PROGRESS');
    assert.equal(wicketUndone.wickets, 0);
    assert.equal(wicketUndone.ballsInCurrentOver, 5);
    assert.equal(wicketUndone.match.target, null);
    assert.ok(wicketUndone.players.find(player => player.activeRole === 'STRIKER' && !player.isOut));
    const endedByRuns = await recordScore(boundaryId, 6);
    assert.equal(endedByRuns.status, 'COMPLETED');
    assert.equal((await undoAction(boundaryId)).status, 'IN_PROGRESS');
    const guestMatch = await createMatch({ team1Name: team1.name, team2Name: team2.name, team1Id: team1.id, team2Id: team2.id, oversLimit: 2 }, user.id);
    const guestStart = await startMatch(guestMatch.id, { battingFirstTeam: team1.name, strikerName: 'Guest', nonStrikerName: 'B', bowlerName: 'C' });
    const guestId = guestStart.innings[0].id;
    await recordScore(guestId, 1);
    await addPlayer(user.id, team1.id, 'Guest');
    const guestUndo = await undoAction(guestId);
    assert.equal(guestUndo.players.find(player => player.playerName === 'Guest')!.playerId, null, 'undo restores saved identity exactly, even if the roster changed');
    await recordExtra(second.id, 'NO_BALL');
    await recordExtra(second.id, 'WIDE');
    assert.equal((await getInnings(second.id))!.match.status, 'COMPLETED');
    const extraUndone = await undoAction(second.id);
    assert.equal(extraUndone.runs, 1);
    assert.equal(extraUndone.ballsInCurrentOver, 0);
    assert.equal(extraUndone.match.status, 'IN_PROGRESS');
  } finally {
    await prisma.match.deleteMany({ where: { ownerId: { in: [user.id, other.id] } } });
    await prisma.user.deleteMany({ where: { id: { in: [user.id, other.id] } } });
    await prisma.$disconnect();
  }
});
